
let allQuizData = [
    {
        kanji:"温度",
        answer:"おんど",
        choices:["おんど","おどん","おんと"]
    },
    {
        kanji:"危険",
        answer:"きけん",
        choices:["きけん","きげん","きかん"]
    },
    {
        kanji:"種類",
        answer:"しゅるい",
        choices:["しゅるい","しゅうるい","しゅれい"]
    },
    {
        kanji:"消す",
        answer:"けす",
        choices:["けす","けし","こす"]
    },
    {
        kanji:"捨てる",
        answer:"すてる",
        choices:["すてる","してる","すれる"]
    },
    {
        kanji:"出す",
        answer:"だす",
        choices:["だす","です","たす"]
    },
    {
        kanji:"分ける",
        answer:"わける",
        choices:["わける","わかる","われる"]
    },
    {
        kanji:"燃える",
        answer:"もえる",
        choices:["もえる","もやる","こえる"]
    },
    {
        kanji:"決める",
        answer:"きめる",
        choices:["きめる","きまる","けめる"]
    },
    {
        kanji:"設定する",
        answer:"せっていする",
        choices:["せっていする","せいってする","せつていする"]
    },
    {
        kanji:"地震",
        answer:"じしん",
        choices:["じしん","ちしん","じじん"]
    },
    {
        kanji:"台風",
        answer:"たいふう",
        choices:["たいふう","だいふう","たいぷう"]
    },
    {
        kanji:"外",
        answer:"そと",
        choices:["そと","ほか","がい"]
    },
    {
        kanji:"声",
        answer:"こえ",
        choices:["こえ","こい","ごえ"]
    },
    {
        kanji:"危ない",
        answer:"あぶない",
        choices:["あぶない","あぶい","あない"]
    },
    {
        kanji:"大切",
        answer:"たいせつ",
        choices:["たいせつ","だいせつ","たいぜつ"]
    },
    {
        kanji:"心配",
        answer:"しんぱい",
        choices:["しんぱい","じんぱい","しんばい"]
    },
    {
        kanji:"集まる",
        answer:"あつまる",
        choices:["あつまる","あつまり","つまる"]
    },
    {
        kanji:"進む",
        answer:"すすむ",
        choices:["すすむ","すすめる","すすめ"]
    },
    {
        kanji:"最近",
        answer:"さいきん",
        choices:["さいきん","さいげん","さいこん"]
    },
    {
        kanji:"授業",
        answer:"じゅぎょう",
        choices:["じゅぎょう","じゅきょう","しゅぎょう"]
    },
    {
        kanji:"問題",
        answer:"もんだい",
        choices:["もんだい","もんたい","ほんだい"]
    },
    {
        kanji:"大変",
        answer:"たいへん",
        choices:["たいへん","だいへん","たいべん"]
    },
    {
        kanji:"困る",
        answer:"こまる",
        choices:["こまる","こもる","こめる"]
    },
    {
        kanji:"違う",
        answer:"ちがう",
        choices:["ちがう","ちかう","ことなる"]
    },
    {
        kanji:"慣れる",
        answer:"なれる",
        choices:["なれる","なられる","なべる"]
    },
    {
        kanji:"増える",
        answer:"ふえる",
        choices:["ふえる","ふやす","ふける"]
    },
    {
        kanji:"笑う",
        answer:"わらう",
        choices:["わらう","わらい","わるう"]
    },
    {
        kanji:"苦労する",
        answer:"くろうする",
        choices:["くろうする","くどうする","くりょうする"]
    },
    {
        kanji:"希望",
        answer:"きぼう",
        choices:["きぼう","きもう","ぎぼう"]
    },
    {
        kanji:"募集",
        answer:"ぼしゅう",
        choices:["ぼしゅう","ぼじゅう","ほしゅう"]
    },
    {
        kanji:"特に",
        answer:"とくに",
        choices:["とくに","どくに","とっくに"]
    },
    {
        kanji:"住む",
        answer:"すむ",
        choices:["すむ","つむ","すまう"]
    },
    {
        kanji:"建てる",
        answer:"たてる",
        choices:["たてる","たつる","けてる"]
    },
    {
        kanji:"続ける",
        answer:"つづける",
        choices:["つづける","つずける","つけづる"]
    },
    {
        kanji:"考える",
        answer:"かんがえる",
        choices:["かんがえる","かがえる","こうがえる"]
    },
    {
        kanji:"役に立つ",
        answer:"やくにたつ",
        choices:["やくにたつ","やくたにつ","やっくにたつ"]
    },
    {
        kanji:"卒業する",
        answer:"そつぎょうする",
        choices:["そつぎょうする","そっぎょうする","そつきょうする"]
    },
    {
        kanji:"留学する",
        answer:"りゅうがくする",
        choices:["りゅうがくする","りょうがくする","りゅがくする"]
    },
    {
        kanji:"野球",
        answer:"やきゅう",
        choices:["やきゅう","やきょう","やくゅう"]
    },
    {
        kanji:"応援",
        answer:"おうえん",
        choices:["おうえん","おうねん","おえん"]
    },
    {
        kanji:"約束",
        answer:"やくそく",
        choices:["やくそく","やっそく","やくぞく"]
    },
    {
        kanji:"得意",
        answer:"とくい",
        choices:["とくい","どくい","とけい"]
    },
    {
        kanji:"伝統的",
        answer:"でんとうてき",
        choices:["でんとうてき","てんとうてき","でんとうでき"]
    },
    {
        kanji:"弱い",
        answer:"よわい",
        choices:["よわい","よあい","じゃくい"]
    },
    {
        kanji:"勝つ",
        answer:"かつ",
        choices:["かつ","まつ","がつ"]
    },
    {
        kanji:"負ける",
        answer:"まける",
        choices:["まける","まげる","あける"]
    },
    {
        kanji:"誘う",
        answer:"さそう",
        choices:["さそう","ささう","ゆそう"]
    },
    {
        kanji:"座る",
        answer:"すわる",
        choices:["すわる","ざわる","すまる"]
    },
    {
        kanji:"共感",
        answer:"きょうかん",
        choices:["きょうかん","きょうがん","きょかん"]
    },
    {
        kanji:"主人公",
        answer:"しゅじんこう",
        choices:["しゅじんこう","しゅにんこう","しゅじこう"]
    },
    {
        kanji:"映像",
        answer:"えいぞう",
        choices:["えいぞう","えぞう","えいそう"]
    },
    {
        kanji:"原作",
        answer:"げんさく",
        choices:["げんさく","けんさく","げんざく"]
    },
    {
        kanji:"歌詞",
        answer:"かし",
        choices:["かし","うたし","かじ"]
    },
    {
        kanji:"俳優",
        answer:"はいゆう",
        choices:["はいゆう","はいよう","ばいゆう"]
    },
    {
        kanji:"お腹",
        answer:"おなか",
        choices:["おなか","おはら","おなこ"]
    },
    {
        kanji:"深み",
        answer:"ふかみ",
        choices:["ふかみ","しんみ","ふくみ"]
    },
    {
        kanji:"演じる",
        answer:"えんじる",
        choices:["えんじる","えんする","えいじる"]
    },
    {
        kanji:"探す",
        answer:"さがす",
        choices:["さがす","さかす","たがす"]
    },
    {
        kanji:"死ぬ",
        answer:"しぬ",
        choices:["しぬ","じぬ","しの"]
    },

    {
        kanji:"引っ越し",
        answer:"ひっこし",
        choices:["ひっこし","ひこっし","ひっこうし"]
    },
    {
        kanji:"家賃",
        answer:"やちん",
        choices:["やちん","かちん","やじん"]
    },
    {
        kanji:"築～年",
        answer:"ちく～ねん",
        choices:["ちく～ねん","きず～ねん","ちっく～ねん"]
    },
    {
        kanji:"住宅地",
        answer:"じゅうたくち",
        choices:["じゅうたくち","じゅたくち","じゅうたくじ"]
    },
    {
        kanji:"荷物",
        answer:"にもつ",
        choices:["にもつ","にもの","かもつ"]
    },
    {
        kanji:"冷蔵庫",
        answer:"れいぞうこ",
        choices:["れいぞうこ","れいそうこ","れぞうこ"]
    },
    {
        kanji:"電子レンジ",
        answer:"でんしレンジ",
        choices:["でんしレンジ","でんじレンジ","てんしレンジ"]
    },
    {
        kanji:"～県",
        answer:"～けん",
        choices:["～けん","～げん","～かん"]
    },
    {
        kanji:"～区",
        answer:"～く",
        choices:["～く","～ぐ","～こ"]
    },

    {
        kanji:"洗面台",
        answer:"せんめんだい",
        choices:["せんめんだい","せいめんだい","せんめんたい"]
    },
    {
        kanji:"洗濯機",
        answer:"せんたくき",
        choices:["せんたくき","せんだくき","せんたきき"]
    },
    {
        kanji:"換気扇",
        answer:"かんきせん",
        choices:["かんきせん","かんけせん","かんきぜん"]
    },
    {
        kanji:"一戸建て",
        answer:"いっこだて",
        choices:["いっこだて","いちこだて","いっこうだて"]
    },
    {
        kanji:"庭",
        answer:"にわ",
        choices:["にわ","には","てい"]
    },
    {
        kanji:"運動",
        answer:"うんどう",
        choices:["うんどう","うんとう","うどう"]
    },
    {
        kanji:"バス停",
        answer:"ばすてい",
        choices:["ばすてい","ばすて","ばすちょう"]
    },
    {
        kanji:"田んぼ",
        answer:"たんぼ",
        choices:["たんぼ","でんぼ","たぼ"]
    },
    {
        kanji:"林",
        answer:"はやし",
        choices:["はやし","り","ばや"]
    },
    {
        kanji:"鳥",
        answer:"とり",
        choices:["とり","どり","とろ"]
    },
    {
        kanji:"注文履歴",
        answer:"ちゅうもんりれき",
        choices:["ちゅうもんりれき","ちゅうもんれき","ちょうもんりれき"]
    },
    {
        kanji:"持ち帰り",
        answer:"もちかえり",
        choices:["もちかえり","まちかえり","もちがえり"]
    },
    {
        kanji:"税込み",
        answer:"ぜいこみ",
        choices:["ぜいこみ","せいこみ","ぜいごみ"]
    },
    {
        kanji:"大盛り",
        answer:"おおもり",
        choices:["おおもり","たいもり","おもり"]
    },
    {
        kanji:"麺",
        answer:"めん",
        choices:["めん","めい","べん"]
    },
    {
        kanji:"送信する",
        answer:"そうしんする",
        choices:["そうしんする","そうじんする","そうせんする"]
    },
    {
        kanji:"混ぜる",
        answer:"まぜる",
        choices:["まぜる","ませる","こんぜる"]
    },
    {
        kanji:"固める",
        answer:"かためる",
        choices:["かためる","こためる","かためり"]
    },
    {
        kanji:"丸める",
        answer:"まるめる",
        choices:["まるめる","まろめる","まるまる"]
    },
    {
        kanji:"煮る",
        answer:"にる",
        choices:["にる","ねる","いる"]
    },
    {
        kanji:"冷凍食品",
        answer:"れいとうしょくひん",
        choices:["れいとうしょくひん","れいどうしょくひん","れいとうしょっぴん"]
    },
    {
        kanji:"果物",
        answer:"くだもの",
        choices:["くだもの","かもの","くだもん"]
    },
    {
        kanji:"農家",
        answer:"のうか",
        choices:["のうか","のか","のうや"]
    },
    {
        kanji:"直接",
        answer:"ちょくせつ",
        choices:["ちょくせつ","ちょくぜつ","ちょうくせつ"]
    },
    {
        kanji:"健康",
        answer:"けんこう",
        choices:["けんこう","げんこう","けんこう"]
    },
    {
        kanji:"栄養",
        answer:"えいよう",
        choices:["えいよう","えよう","えいようう"]
    },
    {
        kanji:"鍋",
        answer:"なべ",
        choices:["なべ","なへ","べな"]
    },
    {
        kanji:"調味料",
        answer:"ちょうみりょう",
        choices:["ちょうみりょう","ちょうみりょう","ちょうみりょ"]
    },
    {
        kanji:"新鮮",
        answer:"しんせん",
        choices:["しんせん","じんせん","しんぜん"]
    },
    {
        kanji:"東むき",
        answer:"ひがしむき",
        choices:["ひがしむき","あずまむき","ひがしむけ"]
    },
    {
        kanji:"自己紹介",
        answer:"じこしょうかい",
        choices:["じこしょうかい","じごしょうかい","じこしょうがい"]
    },
    {
        kanji:"興味",
        answer:"きょうみ",
        choices:["きょうみ","きようみ","こうみ"]
    },
    {
        kanji:"仲間",
        answer:"なかま",
        choices:["なかま","ちゅうかん","なかまち"]
    },
    {
        kanji:"子育て",
        answer:"こそだて",
        choices:["こそだて","こそたて","こいくて"]
    },
    {
        kanji:"児童館",
        answer:"じどうかん",
        choices:["じどうかん","としょかん","けいさつかん"]
    },
    {
        kanji:"掲示板",
        answer:"けいじばん",
        choices:["けいじばん","けじばん","けいしばん"]
    },
    {
        kanji:"掃除",
        answer:"そうじ",
        choices:["そうじ","そうし","そじ"]
    },
    {
        kanji:"次",
        answer:"つぎ",
        choices:["つぎ","つく","つき"]
    },
    {
        kanji:"簡単",
        answer:"かんたん",
        choices:["かんたん","かんだん","けんたん"]
    },
    {
        kanji:"植える",
        answer:"うえる",
        choices:["うえる","うめる","はえる"]
    },
    {
        kanji:"第一印象",
        answer:"だいいちいんしょう",
        choices:["だいいちいんしょう","たいいちいんしょう","だいいちいんそう"]
    },
    {
        kanji:"関心",
        answer:"かんしん",
        choices:["かんしん","かんじん","がんしん"]
    },
    {
        kanji:"背なか",
        answer:"せなか",
        choices:["せすじ","せなか","せきん"]
    },
    {
        kanji:"逆",
        answer:"ぎゃく",
        choices:["ぎゃく","きゃく","ぎゃっく"]
    },
    {
        kanji:"この辺",
        answer:"このへん",
        choices:["このへん","このあたり","このべん"]
    },
    {
        kanji:"清潔",
        answer:"せいけつ",
        choices:["せいけつ","しょうけつ","せいげつ"]
    },
    {
        kanji:"効果的",
        answer:"こうかてき",
        choices:["こうかてき","こうがてき","こうかでき"]
    },
    {
        kanji:"伸ばす",
        answer:"のばす",
        choices:["のばす","のべる","しんばす"]
    },
    {
        kanji:"与える",
        answer:"あたえる",
        choices:["あたえる","あだえる","あてえる"]
    },
    {
        kanji:"整う",
        answer:"ととのう",
        choices:["ととのう","ととのえる","とどのう"]
    },
    {
        kanji:"方言",
        answer:"ほうげん",
        choices:["ほうげん","ほげん","ほうけん"]
    },
    {
        kanji:"目標",
        answer:"もくひょう",
        choices:["もくひょう","もくしょう","ぼくひょう"]
    },
    {
        kanji:"知識",
        answer:"ちしき",
        choices:["ちしき","ちじき","ちせき"]
    },
    {
        kanji:"最初",
        answer:"さいしょ",
        choices:["さいしょ","さいしょう","さいそ"]
    },
    {
        kanji:"悩み",
        answer:"なやみ",
        choices:["なやみ","なまみ","のやみ"]
    },
    {
        kanji:"介護",
        answer:"かいご",
        choices:["かいご","がいご","かいこう"]
    },
    {
        kanji:"吹き替え",
        answer:"ふきかえ",
        choices:["ふきかえ","ふきがえ","ふきけえ"]
    },
    {
        kanji:"足りる",
        answer:"たりる",
        choices:["たりる","たれる","たりうる"]
    },
    {
        kanji:"失敗する",
        answer:"しっぱいする",
        choices:["しっぱいする","しっばいする","しっぱいさる"]
    },
    {
        kanji:"理解する",
        answer:"りかいする",
        choices:["りかいする","りがいする","りけいする"]
    },
    {
        kanji:"登録",
        answer:"とうろく",
        choices:["とうろく","とうりょく","どうろく"]
    },
    {
        kanji:"対象",
        answer:"たいしょう",
        choices:["たいしょう","だいしょう","たいじょう"]
    },
    {
        kanji:"文章",
        answer:"ぶんしょう",
        choices:["ぶんしょう","ぶんじょう","もんしょう"]
    },
    {
        kanji:"表現",
        answer:"ひょうげん",
        choices:["ひょうげん","ひょうけん","びょうげん"]
    },
    {
        kanji:"字まく",
        answer:"じまく",
        choices:["じまく","しまく","じばく"]
    },
    {
        kanji:"～在住",
        answer:"～ざいじゅう",
        choices:["～ざいじゅう","～さいじゅう","～ざいしゅう"]
    },
    {
        kanji:"専門学校",
        answer:"せんもんがっこう",
        choices:["せんもんがっこう","せんもんがこう","せいもんがっこう"]
    },
    {
        kanji:"基礎",
        answer:"きそ",
        choices:["きそ","きぞてき","きしょうてき"]
    },
    {
        kanji:"研究する",
        answer:"けんきゅうする",
        choices:["けんきゅうする","げんきゅうする","けんきょうする"]
    },
    {
        kanji:"助かる",
        answer:"たすかる",
        choices:["たすかる","だすかる","たづかる"]
    },
    {
        kanji:"忘れ物",
        answer:"わすれもの",
        choices:["わすれもの","わすれもん","わすりもの"]
    },
    {
        kanji:"財布",
        answer:"さいふ",
        choices:["さいふ","ざいふ","さいぶ"]
    },
    {
        kanji:"法律",
        answer:"ほうりつ",
        choices:["ほうりつ","ほうりっ","ほうれつ"]
    },
    {
        kanji:"違反",
        answer:"いはん",
        choices:["いはん","ちはん","いばん"]
    },
    {
        kanji:"協力",
        answer:"きょうりょく",
        choices:["きょうりょく","きょうろく","ぎょうりょく"]
    },
    {
        kanji:"鉄道",
        answer:"てつどう",
        choices:["てつどう","てつどう","てつどが"]
    },
    {
        kanji:"提示する",
        answer:"ていじする",
        choices:["ていじする","ていしする","てじする"]
    },
    {
        kanji:"発券する",
        answer:"はっけんする",
        choices:["はっけんする","はつけんする","はっげんする"]
    },
    {
        kanji:"落とす",
        answer:"おとす",
        choices:["おとす","おろす","おつす"]
    },
    {
        kanji:"預ける",
        answer:"あずける",
        choices:["あずける","あづける","あすける"]
    },
    {
        kanji:"払う",
        answer:"はらう",
        choices:["はらう","はろう","ばらう"]
    },
    {
        kanji:"警察",
        answer:"けいさつ",
        choices:["けいさつ","けいざつ","けさつ"]
    },
    {
        kanji:"消防車",
        answer:"しょうぼうしゃ",
        choices:["しょうぼうしゃ","きゅうきゅうしゃ","パトカー"]
    },
    {
        kanji:"救急車",
        answer:"きゅうきゅうしゃ",
        choices:["きゅうきゅうしゃ","きゅきゅうしゃ","きゅうきゅしゃ"]
    },
    {
        kanji:"ひったくり",
        answer:"ひったくり",
        choices:["ひったくり","ひたっくり","ひったぐり"]
    },
    {
        kanji:"交差点",
        answer:"こうさてん",
        choices:["こうさてん","こうさでん","こうさてい"]
    },
    {
        kanji:"～丁目",
        answer:"～ちょうめ",
        choices:["～ちょうめ","～ていめ","～ちょめ"]
    },
    {
        kanji:"～歳",
        answer:"～さい",
        choices:["～さい","～ざい","～せい"]
    },
    {
        kanji:"警報",
        answer:"けいほう",
        choices:["けいほう","けいぼう","けいぽう"]
    },
    {
        kanji:"出張",
        answer:"しゅっちょう",
        choices:["しゅっちょう","しゅつちょう","しゅっしょう"]
    },
    {
        kanji:"曲がる",
        answer:"まがる",
        choices:["まがる","まわる","まける"]
    },
    {
        kanji:"置く",
        answer:"おく",
        choices:["おく","おこ","おけ"]
    },
    {
        kanji:"運命",
        answer:"うんめい",
        choices:["うんめい","うめい","うんみょう"]
    },
    {
        kanji:"糸",
        answer:"いと",
        choices:["いと","しと","いとう"]
    },
    {
        kanji:"恋人",
        answer:"こいびと",
        choices:["こいびと","れんびと","こいひと"]
    },
    {
        kanji:"太陽",
        answer:"たいよう",
        choices:["たいよう","だいよう","たいようう"]
    },
    {
        kanji:"反対",
        answer:"はんたい",
        choices:["はんたい","ばんたい","はんだい"]
    },
    {
        kanji:"若い",
        answer:"わかい",
        choices:["わかい","わこう","じゃくい"]
    },
    {
        kanji:"就職する",
        answer:"しゅうしょくする",
        choices:["しゅうしょくする","しゅしょくする","しゅうそくする"]
    },
    {
        kanji:"退職する",
        answer:"たいしょくする",
        choices:["たいしょくする","だいしょくする","たいそくする"]
    },
    {
        kanji:"覚えている",
        answer:"おぼえている",
        choices:["おぼえている","おぼえてる","おもえている"]
    },
    {
        kanji:"仲良し",
        answer:"なかよし",
        choices:["なかよし","なかよく","ちゅうよし"]
    },
    {
        kanji:"恋愛",
        answer:"れんあい",
        choices:["れんあい","こいあい","れない"]
    },
    {
        kanji:"既読",
        answer:"きどく",
        choices:["きどく","きとく","がいどく"]
    },
    {
        kanji:"好奇心",
        answer:"こうきしん",
        choices:["こうきしん","こうぎしん","こうきじん"]
    },
    {
        kanji:"積極的",
        answer:"せっきょくてき",
        choices:["せっきょくてき","せきょくてき","せっきょうてき"]
    },
    {
        kanji:"悲しい",
        answer:"かなしい",
        choices:["かなしい","かなしい","かなし"]
    },
    {
        kanji:"尊敬する",
        answer:"そんけいする",
        choices:["そんけいする","そんげいする","そんけする"]
    },
    {
        kanji:"実は",
        answer:"じつは",
        choices:["じつは","じちは","じっは"]
    },
    {
        kanji:"例えば",
        answer:"たとえば",
        choices:["たとえば","たどえば","たとえは"]
    },
    {
        kanji:"湖",
        answer:"みずうみ",
        choices:["みずうみ","こう","みずみ"]
    },
    {
        kanji:"雲",
        answer:"くも",
        choices:["くも","ぐも","そら"]
    },
    {
        kanji:"空港",
        answer:"くうこう",
        choices:["くうこう","くこう","そらこう"]
    },
    {
        kanji:"各地",
        answer:"かくち",
        choices:["かくち","かくじ","がくち"]
    },
    {
        kanji:"緑",
        answer:"みどり",
        choices:["みどり","りょ","みとり"]
    },
    {
        kanji:"黄色",
        answer:"きいろ",
        choices:["きいろ","きいろう","おうしょ"]
    },
    {
        kanji:"昔",
        answer:"むかし",
        choices:["むかし","むこう","むし"]
    },
    {
        kanji:"かき氷",
        answer:"かきごおり",
        choices:["かきごおり","かきこおり","かきごり"]
    },
    {
        kanji:"石炭",
        answer:"せきたん",
        choices:["せきたん","いしたん","せったん"]
    },
    {
        kanji:"暖かい",
        answer:"あたたかい",
        choices:["あたたかい","あたかい","あったかい"]
    },
    {
        kanji:"訪れる",
        answer:"おとずれる",
        choices:["おとずれる","おとづれる","たずねる"]
    },
    {
        kanji:"新幹線",
        answer:"しんかんせん",
        choices:["しんかんせん","しんがんせん","しんかんぜん"]
    },
    {
        kanji:"飛行機",
        answer:"ひこうき",
        choices:["ひこうき","ひこうき","ひこうぎ"]
    },
    {
        kanji:"宿泊",
        answer:"しゅくはく",
        choices:["しゅくはく","しゅくばく","しゅうはく"]
    },
    {
        kanji:"和室",
        answer:"わしつ",
        choices:["わしつ","かしつ","わじつ"]
    },
    {
        kanji:"洋室",
        answer:"ようしつ",
        choices:["ようしつ","ようじつ","ようしゅつ"]
    },
    {
        kanji:"お土産",
        answer:"おみやげ",
        choices:["おみやげ","おどさん","おつちさん"]
    },
    {
        kanji:"美術館",
        answer:"びじゅつかん",
        choices:["びじゅつかん","びしゅつかん","びじつかん"]
    },
    {
        kanji:"追加",
        answer:"ついか",
        choices:["ついか","つかい","ついが"]
    },
    {
        kanji:"高級",
        answer:"こうきゅう",
        choices:["こうきゅう","こうぎゅう","こうきゅ"]
    },
    {
        kanji:"疲れる",
        answer:"つかれる",
        choices:["つかれる","つがれる","つかねる"]
    },
    {
        kanji:"給料",
        answer:"きゅうりょう",
        choices:["きゅうりょう","ぎゅうりょう","きゅりょう"]
    },
    {
        kanji:"欠勤",
        answer:"けっきん",
        choices:["けっきん","けつきん","けっこん"]
    },
    {
        kanji:"会議",
        answer:"かいぎ",
        choices:["かいぎ","がいぎ","かぎ"]
    },
    {
        kanji:"残業",
        answer:"ざんぎょう",
        choices:["ざんぎょう","さんぎょう","ざんきょう"]
    },
    {
        kanji:"規則",
        answer:"きそく",
        choices:["きそく","ぎそく","きぞく"]
    },
    {
        kanji:"髪型",
        answer:"かみがた",
        choices:["かみがた","かみかた","はつがた"]
    },
    {
        kanji:"不可",
        answer:"ふか",
        choices:["ふか","ぶか","ふが"]
    },
    {
        kanji:"～係",
        answer:"～がかり",
        choices:["～がかり","～かかり","～ががり"]
    },
    {
        kanji:"速い",
        answer:"はやい",
        choices:["はやい","すごい","はやし"]
    },
    {
        kanji:"遅刻する",
        answer:"ちこくする",
        choices:["ちこくする","じこくする","ちこうする"]
    },
    {
        kanji:"輸出",
        answer:"ゆしゅつ",
        choices:["ゆしゅつ","ゆしょう","ゆじゅつ"]
    },
    {
        kanji:"作成",
        answer:"さくせい",
        choices:["さくせい","さくしょう","さくぜい"]
    },
    {
        kanji:"未経験",
        answer:"みけいけん",
        choices:["みけいけん","びけいけん","みけいげん"]
    },
    {
        kanji:"順調",
        answer:"じゅんちょう",
        choices:["じゅんちょう","しゅんちょう","じゅんじょう"]
    },
    {
        kanji:"報告",
        answer:"ほうこく",
        choices:["ほうこく","ほうごく","ほこうこく"]
    },
    {
        kanji:"努力",
        answer:"どりょく",
        choices:["どりょく","どりょうく","とりょく"]
    },
    {
        kanji:"非常に",
        answer:"ひじょうに",
        choices:["ひじょうに","ひしょうに","ひじょに"]
    },
    {
        kanji:"充実する",
        answer:"じゅうじつする",
        choices:["じゅうじつする","じゅじつする","じゅうしつする"]
    },
    {
        kanji:"答える",
        answer:"こたえる",
        choices:["こたえる","こだえる","こたいる"]
    },
    {
        kanji:"向いている",
        answer:"むいている",
        choices:["むいている","むいでいる","むけている"]
    },

    {
        kanji:"名前",
        answer:"なまえ",
        choices:["なまえ","なめえ","なまい"]
    },
    {
        kanji:"高校",
        answer:"こうこう",
        choices:["こうこう","こうごう","ここう"]
    },
    {
        kanji:"大学",
        answer:"だいがく",
        choices:["だいがく","たいがく","だいかく"]
    },
    {
        kanji:"練習",
        answer:"れんしゅう",
        choices:["れんしゅう","れんしょう","れんじゅう"]
    },
    {
        kanji:"漢字",
        answer:"かんじ",
        choices:["かんじ","かんし","がんじ"]
    },
    {
        kanji:"無料",
        answer:"むりょう",
        choices:["むりょう","むりょ","ぶりょう"]
    },
    {
        kanji:"言う",
        answer:"いう",
        choices:["いう","ゆう","いうう"]
    },
    {
        kanji:"書く",
        answer:"かく",
        choices:["かく","かこ","がく"]
    },
    {
        kanji:"貸す",
        answer:"かす",
        choices:["かす","だす","かつ"]
    },
    {
        kanji:"教える",
        answer:"おしえる",
        choices:["おしえる","おせえる","おぼえる"]
    },
    {
        kanji:"説明する",
        answer:"せつめいする",
        choices:["せつめいする","せつめする","せつべいする"]
    },

    {
        kanji:"父",
        answer:"ちち",
        choices:["ちち","はは","と"]
    },
    {
        kanji:"午前",
        answer:"ごぜん",
        choices:["ごぜん","こうぜん","ごせん"]
    },
    {
        kanji:"午後",
        answer:"ごご",
        choices:["ごご","こうご","ごこう"]
    },
    {
        kanji:"教科書",
        answer:"きょうかしょ",
        choices:["きょうかしょ","きょうかしょう","きょうがしょ"]
    },
    {
        kanji:"教室",
        answer:"きょうしつ",
        choices:["きょうしつ","きょうじつ","きょしつ"]
    },
    {
        kanji:"先生",
        answer:"せんせい",
        choices:["せんせい","せんぜい","せんしょう"]
    },
    {
        kanji:"全部",
        answer:"ぜんぶ",
        choices:["ぜんぶ","せんぶ","ぜんぷ"]
    },
    {
        kanji:"～回",
        answer:"～かい",
        choices:["～かい","～がい","～え"]
    },
    {
        kanji:"参加する",
        answer:"さんかする",
        choices:["さんかする","ざんかする","さんがする"]
    },
    {
        kanji:"用意する",
        answer:"よういする",
        choices:["よういする","ようする","ようえする"]
    },

    {
        kanji:"水",
        answer:"みず",
        choices:["みず","す","みつ"]
    },
    {
        kanji:"飲み物",
        answer:"のみもの",
        choices:["のみもの","のみもん","のみぶつ"]
    },
    {
        kanji:"お茶",
        answer:"おちゃ",
        choices:["おちゃ","おさ","おちや"]
    },
    {
        kanji:"お酒",
        answer:"おさけ",
        choices:["おさけ","おざけ","おしゅ"]
    },
    {
        kanji:"材料",
        answer:"ざいりょう",
        choices:["ざいりょう","さいりょう","ざりょう"]
    },
    {
        kanji:"野菜",
        answer:"やさい",
        choices:["やさい","のさい","やざい"]
    },
    {
        kanji:"牛肉",
        answer:"ぎゅうにく",
        choices:["ぎゅうにく","きゅうにく","ぎゅにく"]
    },
    {
        kanji:"豚肉",
        answer:"ぶたにく",
        choices:["ぶたにく","とんにく","ぶだにく"]
    },
    {
        kanji:"皿",
        answer:"さら",
        choices:["さら","ざら","さらい"]
    },
    {
        kanji:"売る",
        answer:"うる",
        choices:["うる","うれる","おる"]
    },
    {
        kanji:"持って行く",
        answer:"もっていく",
        choices:["もっていく","もってゆく","もていく"]
    },
    
    {
        kanji:"魚",
        answer:"さかな",
        choices:["さかな","うおう","さかなあ"]
    },
    {
        kanji:"卵",
        answer:"たまご",
        choices:["たまご","たごま","らんこ"]
    },
    {
        kanji:"料理",
        answer:"りょうり",
        choices:["りょうり","りょり","りょうりい"]
    },
    {
        kanji:"お湯",
        answer:"おゆ",
        choices:["おゆ","おみず","ゆう"]
    },
    {
        kanji:"調理方法",
        answer:"ちょうりほうほう",
        choices:["ちょうりほうほう","ちょうりぼうほう","ちょうりほほう"]
    },
    {
        kanji:"少し",
        answer:"すこし",
        choices:["すこし","しょうし","すくし"]
    },
    {
        kanji:"味",
        answer:"あじ",
        choices:["あじ","みん","あし"]
    },
    {
        kanji:"甘い",
        answer:"あまい",
        choices:["あまい","うまい","あない"]
    },
    {
        kanji:"辛い",
        answer:"からい",
        choices:["からい","つい","しんらい"]
    },
    {
        kanji:"苦手",
        answer:"にがて",
        choices:["にがて","くて","にがで"]
    },
    {
        kanji:"お願いします",
        answer:"おねがいします",
        choices:["おねがいします","おながいします","おねいます"]
    },

    {
        kanji:"家",
        answer:"いえ",
        choices:["いえ","う","やい"]
    },
    {
        kanji:"コピー機",
        answer:"コピーき",
        choices:["コピーき","コピーぎ","こぴーき"]
    },
    {
        kanji:"数字",
        answer:"すうじ",
        choices:["すうじ","すじ","すうし"]
    },
    {
        kanji:"電気",
        answer:"でんき",
        choices:["でんき","てんき","でんぎ"]
    },
    {
        kanji:"音",
        answer:"おと",
        choices:["おと","ねん","おん"]
    },
    {
        kanji:"机",
        answer:"つくえ",
        choices:["つくえ","つぐえ","き"]
    },
    {
        kanji:"都合",
        answer:"つごう",
        choices:["つごう","とごう","つこう"]
    },
    {
        kanji:"悪い",
        answer:"わるい",
        choices:["わるい","あくい","わりい"]
    },
    {
        kanji:"動く",
        answer:"うごく",
        choices:["うごく","どうく","うこく"]
    },
    {
        kanji:"使う",
        answer:"つかう",
        choices:["つかう","つこう","しよう"]
    },
    {
        kanji:"終わる",
        answer:"おわる",
        choices:["おわる","おえる","しゅうわる"]
    },

    {
        kanji:"上",
        answer:"うえ",
        choices:["うえ","うい","うわ"]
    },
    {
        kanji:"用事",
        answer:"ようじ",
        choices:["ようじ","ようし","ようち"]
    },
    {
        kanji:"氏名",
        answer:"しめい",
        choices:["しめい","じめい","しみょう"]
    },
    {
        kanji:"理由",
        answer:"りゆう",
        choices:["りゆう","りよう","りゅう"]
    },
    {
        kanji:"連絡先",
        answer:"れんらくさき",
        choices:["れんらくさき","れんらくせん","れんらくまえ"]
    },
    {
        kanji:"別に",
        answer:"べつに",
        choices:["べつに","べっに","べつり"]
    },
    {
        kanji:"早く",
        answer:"はやく",
        choices:["はやく","そうく","はやいく"]
    },
    {
        kanji:"吸う",
        answer:"すう",
        choices:["すう","きゅう","すおう"]
    },
    {
        kanji:"取る",
        answer:"とる",
        choices:["とる","どる","とれる"]
    },
    {
        kanji:"帰る",
        answer:"かえる",
        choices:["かえる","かえす","きえる"]
    },
    {
        kanji:"伝える",
        answer:"つたえる",
        choices:["つたえる","でんえる","つだえる"]
    },

    {
        kanji:"月",
        answer:"つき",
        choices:["つき","げ","が"]
    },
    {
        kanji:"熱",
        answer:"ねつ",
        choices:["ねつ","あつうう","ねっ"]
    },
    {
        kanji:"薬",
        answer:"くすり",
        choices:["くすり","や","くさり"]
    },
    {
        kanji:"病気",
        answer:"びょうき",
        choices:["びょうき","ひょうき","びょうぎ"]
    },
    {
        kanji:"病院",
        answer:"びょういん",
        choices:["びょういん","ひょういん","びよういん"]
    },
    {
        kanji:"医者",
        answer:"いしゃ",
        choices:["いしゃ","いじゃ","いさ"]
    },
    {
        kanji:"住所",
        answer:"じゅうしょ",
        choices:["じゅうしょ","じゅうじょ","じゅしょ"]
    },
    {
        kanji:"～才",
        answer:"～さい",
        choices:["～さい","～ざい","～せい"]
    },
    {
        kanji:"痛い",
        answer:"いたい",
        choices:["いたい","いたえ","つらい"]
    },
    {
        kanji:"眠い",
        answer:"ねむい",
        choices:["ねむい","ねぶい","ねもい"]
    },
    {
        kanji:"寝る",
        answer:"ねる",
        choices:["ねる","ねれる","ねろ"]
    },
    {
        kanji:"記入する",
        answer:"きにゅうする",
        choices:["きにゅうする","きゅうにする","きにゅする"]
    },
    {
        kanji:"車",
        answer:"くるま",
        choices:["くるま","ぐるま","くるみ"]
    },
    {
        kanji:"体",
        answer:"からだ",
        choices:["からだ","かだら","た"]
    },
    {
        kanji:"顔",
        answer:"かお",
        choices:["かお","がお","かこ"]
    },
    {
        kanji:"目",
        answer:"め",
        choices:["め","もくく","ま"]
    },
    {
        kanji:"耳",
        answer:"みみ",
        choices:["みみ","じん","みも"]
    },
    {
        kanji:"口",
        answer:"くち",
        choices:["くち","こん","ぐち"]
    },
    {
        kanji:"頭",
        answer:"あたま",
        choices:["あたま","かし","ずん"]
    },
    {
        kanji:"足",
        answer:"あし",
        choices:["あし","そ","あじ"]
    },
    {
        kanji:"手",
        answer:"て",
        choices:["て","しゅく","で"]
    },
    {
        kanji:"起きる",
        answer:"おきる",
        choices:["おきる","おこる","おける"]
    },
    {
        kanji:"歩く",
        answer:"あるく",
        choices:["あるく","あるけ","ありく"]
    },
    {
        kanji:"走る",
        answer:"はしる",
        choices:["はしる","はいる","はせる"]
    },

    {
        kanji:"お父さん",
        answer:"おとうさん",
        choices:["おとうさん","おとさん","おどうさん"]
    },
    {
        kanji:"お母さん",
        answer:"おかあさん",
        choices:["おかあさん","おがあさん","おとうさん"]
    },
    {
        kanji:"兄",
        answer:"あに",
        choices:["あに","に","あね"]
    },
    {
        kanji:"お兄さん",
        answer:"おにいさん",
        choices:["おにいさん","おにさん","おねえさん"]
    },
    {
        kanji:"姉",
        answer:"あね",
        choices:["あね","あに","ねえん"]
    },
    {
        kanji:"お姉さん",
        answer:"おねえさん",
        choices:["おねえさん","おねさん","おにいさん"]
    },
    {
        kanji:"弟",
        answer:"おとうと",
        choices:["おとうと","おとと","おとう"]
    },
    {
        kanji:"妹",
        answer:"いもうと",
        choices:["いもうと","いもと","もうと"]
    },
    {
        kanji:"夫",
        answer:"おっと",
        choices:["おっと","ふん","おとこ"]
    },
    {
        kanji:"妻",
        answer:"つま",
        choices:["つま","さいふ","つめ"]
    },
    {
        kanji:"両親",
        answer:"りょうしん",
        choices:["りょうしん","りょしん","りょうせん"]
    },

    {
        kanji:"男の子",
        answer:"おとこのこ",
        choices:["おとこのこ","おとこご","おんなのこ"]
    },
    {
        kanji:"女の子",
        answer:"おんなのこ",
        choices:["おんなのこ","おんなご","おとこのこ"]
    },
    {
        kanji:"お祝い",
        answer:"おいわい",
        choices:["おいわい","おいあい","おいわえ"]
    },
    {
        kanji:"誕生日",
        answer:"たんじょうび",
        choices:["たんじょうび","たんしょうび","だんじょうび"]
    },
    {
        kanji:"結婚",
        answer:"けっこん",
        choices:["けっこん","けつこん","げっこん"]
    },
    {
        kanji:"時計",
        answer:"とけい",
        choices:["とけい","どけい","とけ"]
    },
    {
        kanji:"幸せ",
        answer:"しあわせ",
        choices:["しあわせ","こうふく","しあせ"]
    },
    {
        kanji:"生まれる",
        answer:"うまれる",
        choices:["うまれる","うれる","いまれる"]
    },
    {
        kanji:"思う",
        answer:"おもう",
        choices:["おもう","おもうう","おぼう"]
    },
    {
        kanji:"選ぶ",
        answer:"えらぶ",
        choices:["えらぶ","えらむ","せらぶ"]
    },
    {
        kanji:"合格する",
        answer:"ごうかくする",
        choices:["ごうかくする","こうかくする","ごかくする"]
    },

    {
        kanji:"山",
        answer:"やま",
        choices:["やま","さい","やも"]
    },
    {
        kanji:"川",
        answer:"かわ",
        choices:["かわ","がわ","せんこ"]
    },
    {
        kanji:"海",
        answer:"うみ",
        choices:["うみ","かいし","うめ"]
    },
    {
        kanji:"島",
        answer:"しま",
        choices:["しま","とお","しまう"]
    },
    {
        kanji:"森",
        answer:"もり",
        choices:["もり","し","もる"]
    },
    {
        kanji:"客",
        answer:"きゃく",
        choices:["きゃく","きゃっく","く"]
    },
    {
        kanji:"観光地",
        answer:"かんこうち",
        choices:["かんこうち","かんこち","かんごうち"]
    },
    {
        kanji:"意味",
        answer:"いみ",
        choices:["いみ","いみい","いび"]
    },
    {
        kanji:"経験",
        answer:"けいけん",
        choices:["けいけん","けいかん","けけん"]
    },
    {
        kanji:"意志",
        answer:"いし",
        choices:["いし","いじ","いち"]
    },
    {
        kanji:"立つ",
        answer:"たつ",
        choices:["たつ","たてる","だつ"]
    },
    {
        kanji:"泣く",
        answer:"なく",
        choices:["なく","なくう","なくる"]
    },
{
        kanji:"写真",
        answer:"しゃしん",
        choices:["しゃしん","しゃじん","さしん"]
    },
    {
        kanji:"歌",
        answer:"うた",
        choices:["うた","かい","うだ"]
    },
    {
        kanji:"歌手",
        answer:"かしゅ",
        choices:["かしゅ","うたしゅ","かて"]
    },
    {
        kanji:"上手",
        answer:"じょうず",
        choices:["じょうず","じょうつ","じょず"]
    },
    {
        kanji:"明るい",
        answer:"あかるい",
        choices:["あかるい","あかい","あけるい"]
    },
    {
        kanji:"長い",
        answer:"ながい",
        choices:["ながい","ちょうい","ながえ"]
    },
    {
        kanji:"短い",
        answer:"みじかい",
        choices:["みじかい","たんい","みしかい"]
    },
    {
        kanji:"着る",
        answer:"きる",
        choices:["きる","ぎる","きえる"]
    },
    {
        kanji:"立つ",
        answer:"たつ",
        choices:["たつ","だつ","たてる"]
    },
    {
        kanji:"泣く",
        answer:"なく",
        choices:["なく","なくす","なる"]
    },

    {
        kanji:"注文",
        answer:"ちゅうもん",
        choices:["ちゅうもん","ちょうもん","じゅうもん"]
    },
    {
        kanji:"会計",
        answer:"かいけい",
        choices:["かいけい","がいけい","かいせい"]
    },
    {
        kanji:"予約",
        answer:"よやく",
        choices:["よやく","ようやく","よがく"]
    },
    {
        kanji:"電話番号",
        answer:"でんわばんごう",
        choices:["でんわばんごう","でんわはんごう","でんわばんこう"]
    },
    {
        kanji:"～様",
        answer:"～さま",
        choices:["～さま","～ようん","～さん"]
    },
    {
        kanji:"ご飯",
        answer:"ごはん",
        choices:["ごはん","ごへん","こはん"]
    },
    {
        kanji:"牛乳",
        answer:"ぎゅうにゅう",
        choices:["ぎゅうにゅう","きゅうにゅう","ぎゅにゅう"]
    },
    {
        kanji:"生",
        answer:"なま",
        choices:["なま","せ","しょ"]
    },
    {
        kanji:"禁煙",
        answer:"きんえん",
        choices:["きんえん","ぎんえん","きねん"]
    },
    {
        kanji:"自由",
        answer:"じゆう",
        choices:["じゆう","しゆう","じよう"]
    },

    {
        kanji:"塩",
        answer:"しお",
        choices:["しお","えんこ","しょ"]
    },
    {
        kanji:"油",
        answer:"あぶら",
        choices:["あぶら","ゆうう","あぷら"]
    },
    {
        kanji:"量",
        answer:"りょう",
        choices:["りょう","りょうう","よう"]
    },
    {
        kanji:"～方",
        answer:"～かた",
        choices:["～かた","～ほ","～が"]
    },
    {
        kanji:"～屋",
        answer:"～や",
        choices:["～や","～お","～おくや"]
    },
    {
        kanji:"満足",
        answer:"まんぞく",
        choices:["まんぞく","ばんぞく","まんそく"]
    },
    {
        kanji:"切る",
        answer:"きる",
        choices:["きる","ぎる","きえる"]
    },
    {
        kanji:"焼く",
        answer:"やく",
        choices:["やく","やける","やっく"]
    },
    {
        kanji:"入れる",
        answer:"いれる",
        choices:["いれる","はいる","いれう"]
    },

    {
        kanji:"自然",
        answer:"しぜん",
        choices:["しぜん","じぜん","しせん"]
    },
    {
        kanji:"交通",
        answer:"こうつう",
        choices:["こうつう","こうどう","こうとお"]
    },
    {
        kanji:"船",
        answer:"ふね",
        choices:["ふね","せ","ぶね"]
    },
    {
        kanji:"自転車",
        answer:"じてんしゃ",
        choices:["じてんしゃ","してんしゃ","じでんしゃ"]
    },
    {
        kanji:"旅館",
        answer:"りょかん",
        choices:["りょかん","りょうかん","りょこん"]
    },
    {
        kanji:"東京",
        answer:"とうきょう",
        choices:["とうきょう","ときょう","どうきょう"]
    },
    {
        kanji:"計画",
        answer:"けいかく",
        choices:["けいかく","げいかく","けいがく"]
    },
    {
        kanji:"遊ぶ",
        answer:"あそぶ",
        choices:["あそぶ","あそう","あすぶ"]
    },
    {
        kanji:"調べる",
        answer:"しらべる",
        choices:["しらべる","しらべ","くらべる"]
    },
    {
        kanji:"出発する",
        answer:"しゅっぱつする",
        choices:["しゅっぱつする","しゅつぱつする","しゅっぱっする"]
    },

    {
        kanji:"運転",
        answer:"うんてん",
        choices:["うんてん","うんでん","うてん"]
    },
    {
        kanji:"事故",
        answer:"じこ",
        choices:["じこ","しこ","じこう"]
    },
    {
        kanji:"故障",
        answer:"こしょう",
        choices:["こしょう","ごしょう","こうしょう"]
    },
    {
        kanji:"指定席",
        answer:"していせき",
        choices:["していせき","していぜき","してせき"]
    },
    {
        kanji:"週末",
        answer:"しゅうまつ",
        choices:["しゅうまつ","しゅまつ","じゅうまつ"]
    },
    {
        kanji:"絵",
        answer:"え",
        choices:["え","かいん","ええ"]
    },
    {
        kanji:"空",
        answer:"そら",
        choices:["そら","からい","く"]
    },
    {
        kanji:"泳ぐ",
        answer:"およぐ",
        choices:["およぐ","およげる","おようぐ"]
    },
    {
        kanji:"光る",
        answer:"ひかる",
        choices:["ひかる","ひがる","ぴかる"]
    },
    {
        kanji:"到着する",
        answer:"とうちゃくする",
        choices:["とうちゃくする","どうちゃくする","とうじゃくする"]
    },

    {
        kanji:"お知らせ",
        answer:"おしらせ",
        choices:["おしらせ","おしらぜ","おしらす"]
    },
    {
        kanji:"今月",
        answer:"こんげつ",
        choices:["こんげつ","こんげち","こんせつ"]
    },
    {
        kanji:"水道",
        answer:"すいどう",
        choices:["すいどう","みずどう","すいとう"]
    },
    {
        kanji:"工事",
        answer:"こうじ",
        choices:["こうじ","こうし","こうち"]
    },
    {
        kanji:"広場",
        answer:"ひろば",
        choices:["ひろば","こうば","ひろは"]
    },
    {
        kanji:"場合",
        answer:"ばあい",
        choices:["ばあい","ばいあい","ばえい"]
    },
    {
        kanji:"中止",
        answer:"ちゅうし",
        choices:["ちゅうし","ちゅうじ","じゅうし"]
    },
    {
        kanji:"条件",
        answer:"じょうけん",
        choices:["じょうけん","しょうけん","じょうげん"]
    },
    {
        kanji:"～以上",
        answer:"～いじょう",
        choices:["～いじょう","～いしょう","～じょう"]
    },
    {
        kanji:"開く",
        answer:"ひらく",
        choices:["ひらく","あく","かいく"]
    },
    {
        kanji:"生産する",
        answer:"せいさんする",
        choices:["せいさんする","しょうさんする","せいざんする"]
    },

    {
        kanji:"来年",
        answer:"らいねん",
        choices:["らいねん","らいせん","ないねん"]
    },
    {
        kanji:"会場",
        answer:"かいじょう",
        choices:["かいじょう","がいじょう","かいしょう"]
    },
    {
        kanji:"世界",
        answer:"せかい",
        choices:["せかい","せがい","せたい"]
    },
    {
        kanji:"体験",
        answer:"たいけん",
        choices:["たいけん","だいけん","たいげん"]
    },
    {
        kanji:"国際交流",
        answer:"こくさいこうりゅう",
        choices:["こくさいこうりゅう","こくせいこうりゅう","こくさいこうりょう"]
    },
    {
        kanji:"禁止",
        answer:"きんし",
        choices:["きんし","ぎんし","きんじ"]
    },
    {
        kanji:"紙",
        answer:"かみ",
        choices:["かみ","がみ","しわ"]
    },
    {
        kanji:"始まる",
        answer:"はじまる",
        choices:["はじまる","はしまる","はじめる"]
    },
    {
        kanji:"申し込む",
        answer:"もうしこむ",
        choices:["もうしこむ","もうしごむ","もじこむ"]
    },
    
    {
        kanji:"今年",
        answer:"ことし",
        choices:["ことし","こんねん","ことせ"]
    },
    {
        kanji:"昨年",
        answer:"さくねん",
        choices:["さくねん","さっねん","さくせん"]
    },
    {
        kanji:"毎年",
        answer:"まいとし",
        choices:["まいとし","まいねい","まいどし"]
    },
    {
        kanji:"文化",
        answer:"ぶんか",
        choices:["ぶんか","ぶんが","もんか"]
    },
    {
        kanji:"祭り",
        answer:"まつり",
        choices:["まつり","まっり","さいり"]
    },
    {
        kanji:"正月",
        answer:"しょうがつ",
        choices:["しょうがつ","しょうげつ","せいがつ"]
    },
    {
        kanji:"～式",
        answer:"～しき",
        choices:["～しき","～しぎ","～せき"]
    },
    {
        kanji:"大人",
        answer:"おとな",
        choices:["おとな","だいにん","たいじん"]
    },
    {
        kanji:"米",
        answer:"こめ",
        choices:["こめ","べ","まう"]
    },
    {
        kanji:"特別",
        answer:"とくべつ",
        choices:["とくべつ","どくべつ","とくべっ"]
    },

    {
        kanji:"服",
        answer:"ふく",
        choices:["ふく","ぶく","ようふく"]
    },
    {
        kanji:"袋",
        answer:"ふくろ",
        choices:["ふくろ","ぶくろ","ふころ"]
    },
    {
        kanji:"自分",
        answer:"じぶん",
        choices:["じぶん","しぶん","じふん"]
    },
    {
        kanji:"店長",
        answer:"てんちょう",
        choices:["てんちょう","でんちょう","てんしょう"]
    },
    {
        kanji:"全員",
        answer:"ぜんいん",
        choices:["ぜんいん","せんいん","ぜにん"]
    },
    {
        kanji:"習慣",
        answer:"しゅうかん",
        choices:["しゅうかん","じゅうかん","しゅかん"]
    },
    {
        kanji:"普通",
        answer:"ふつう",
        choices:["ふつう","ふどう","ぶつう"]
    },
    {
        kanji:"暗い",
        answer:"くらい",
        choices:["くらい","ぐらい","くらえ"]
    },
    {
        kanji:"怒る",
        answer:"おこる",
        choices:["おこる","いかる","おごる"]
    },
    {
        kanji:"入院する",
        answer:"にゅういんする",
        choices:["にゅういんする","にゅいんする","にゅうえんする"]
    },
    {
        kanji:"案内する",
        answer:"あんないする",
        choices:["あんないする","あんないさる","あんだいする"]
    },

    {
        kanji:"色",
        answer:"いろ",
        choices:["いろ","しょ","いら"]
    },
    {
        kanji:"赤",
        answer:"あか",
        choices:["あか","せ","あけ"]
    },
    {
        kanji:"青",
        answer:"あお",
        choices:["あお","い","あう"]
    },
    {
        kanji:"黒",
        answer:"くろ",
        choices:["くろ","く","ぐろ"]
    },
    {
        kanji:"白",
        answer:"しろ",
        choices:["しろ","は","びゃく"]
    },
    {
        kanji:"女性",
        answer:"じょせい",
        choices:["じょせい","じょうせい","しょせい"]
    },
    {
        kanji:"男性",
        answer:"だんせい",
        choices:["だんせい","たんせい","だんしょう"]
    },
    {
        kanji:"急に",
        answer:"きゅうに",
        choices:["きゅうに","きゅに","きょうに"]
    },
    {
        kanji:"営業する",
        answer:"えいぎょうする",
        choices:["えいぎょうする","えいきょうする","えいぎょする"]
    },
    {
        kanji:"来内する",
        answer:"らいないする",
        choices:["らいないする","らいだいする","らいないさる"]
    },

    {
        kanji:"商品",
        answer:"しょうひん",
        choices:["しょうひん","しょうびん","しょうへん"]
    },
    {
        kanji:"値段",
        answer:"ねだん",
        choices:["ねだん","ちだん","ねたん"]
    },
    {
        kanji:"価格",
        answer:"かかく",
        choices:["かかく","がかく","かがく"]
    },
    {
        kanji:"消費税",
        answer:"しょうひぜい",
        choices:["しょうひぜい","しょうひせい","しょうびぜい"]
    },
    {
        kanji:"税別",
        answer:"ぜいべつ",
        choices:["ぜいべつ","せいべつ","ぜいべっ"]
    },
    {
        kanji:"店員",
        answer:"てんいん",
        choices:["てんいん","でんいん","てにん"]
    },
    {
        kanji:"親切",
        answer:"しんせつ",
        choices:["しんせつ","じんせつ","しんぜつ"]
    },
    {
        kanji:"重い",
        answer:"おもい",
        choices:["おもい","おおい","おもう"]
    },
    {
        kanji:"軽い",
        answer:"かるい",
        choices:["かるい","がるい","かろい"]
    },
    {
        kanji:"変わる",
        answer:"かわる",
        choices:["かわる","かえる","がわる"]
    },

    {
        kanji:"市",
        answer:"し",
        choices:["し","い","しい"]
    },
    {
        kanji:"料金",
        answer:"りょうきん",
        choices:["りょうきん","りょうぎん","りょうけん"]
    },
    {
        kanji:"図書館",
        answer:"としょかん",
        choices:["としょかん","ずしょかん","としょうかん"]
    },
    {
        kanji:"道具",
        answer:"どうぐ",
        choices:["どうぐ","とうぐ","どうく"]
    },
    {
        kanji:"～点",
        answer:"～てん",
        choices:["～てん","～でん","～せん"]
    },
    {
        kanji:"必要",
        answer:"ひつよう",
        choices:["ひつよう","ひっよう","ひつよ"]
    },
    {
        kanji:"借りる",
        answer:"かりる",
        choices:["かりる","かえる","からる"]
    },
    {
        kanji:"返す",
        answer:"かえす",
        choices:["かえす","かえる","がえす"]
    },
    {
        kanji:"開く",
        answer:"あく",
        choices:["あく","ひく","かいく"]
    },
    {
        kanji:"閉まる",
        answer:"しまる",
        choices:["しまる","しめる","じまる"]
    },
    {
        kanji:"利用する",
        answer:"りようする",
        choices:["りようする","りゅうようする","りよする"]
    },

    {
        kanji:"外国",
        answer:"がいこく",
        choices:["がいこく","かいこく","がいごく"]
    },
    {
        kanji:"情報",
        answer:"じょうほう",
        choices:["じょうほう","しょうほう","じょうぼう"]
    },
    {
        kanji:"相談",
        answer:"そうだん",
        choices:["そうだん","そうたん","ぞうだん"]
    },
    {
        kanji:"質問",
        answer:"しつもん",
        choices:["しつもん","しちもん","しつほん"]
    },
    {
        kanji:"窓口",
        answer:"まどぐち",
        choices:["まどぐち","まどくち","そうぐち"]
    },
    {
        kanji:"郵便局",
        answer:"ゆうびんきょく",
        choices:["ゆうびんきょく","ゆびんきょく","ゆうべんきょく"]
    },
    {
        kanji:"近所",
        answer:"きんじょ",
        choices:["きんじょ","きんしょ","こんじょ"]
    },
    {
        kanji:"自動",
        answer:"じどう",
        choices:["じどう","しどう","じとう"]
    },
    {
        kanji:"洗う",
        answer:"あらう",
        choices:["あらう","せんう","あろう"]
    },
    {
        kanji:"入力する",
        answer:"にゅうりょくする",
        choices:["にゅうりょくする","にゅうろくする","にゅりょくする"]
    },
    {
        kanji:"名前",
        answer:"なまえ",
        choices:["なまえ","なめえ","なまい"]
    },
    {
        kanji:"国",
        answer:"くに",
        choices:["くに","く","ぐに"]
    },
    {
        kanji:"私",
        answer:"わたし",
        choices:["わたし","わだし","わたち"]
    },
    {
        kanji:"日本",
        answer:"にほん",
        choices:["にほん","にっぽん","にほん"]
    },
    {
        kanji:"父",
        answer:"ちち",
        choices:["ちち","はは","と"]
    },
    {
        kanji:"母",
        answer:"はは",
        choices:["はは","ちち","おかあ"]
    },
    {
        kanji:"子ども",
        answer:"こども",
        choices:["こども","こどもう","こどま"]
    },
    {
        kanji:"水",
        answer:"みず",
        choices:["みず","みづ","すい"]
    },
    {
        kanji:"食べます",
        answer:"たべます",
        choices:["たべます","たへます","たべました"]
    },
    {
        kanji:"飲みます",
        answer:"のみます",
        choices:["のみます","のみました","たべます"]
    },
    {
        kanji:"魚",
        answer:"さかな",
        choices:["さかな","うおう","さけな"]
    },
    {
        kanji:"肉",
        answer:"にく",
        choices:["にく","にぐ","しし"]
    },
    {
        kanji:"好き",
        answer:"すき",
        choices:["すき","ずき","すぎ"]
    },
    {
        kanji:"家",
        answer:"いえ",
        choices:["いえ","う","や"]
    },
    {
        kanji:"新しい",
        answer:"あたらしい",
        choices:["あたらしい","あだらしい","あたらし"]
    },
    {
        kanji:"広い",
        answer:"ひろい",
        choices:["ひろい","ひろう","びろい"]
    },
    {
        kanji:"古い",
        answer:"ふるい",
        choices:["ふるい","ふろい","こい"]
    },
    {
        kanji:"上",
        answer:"うえ",
        choices:["うえ","した","なか"]
    },
    {
        kanji:"下",
        answer:"した",
        choices:["した","うえ","うしろ"]
    },
    {
        kanji:"中",
        answer:"なか",
        choices:["なか","うえ","うち"]
    },

    {
        kanji:"月",
        answer:"げつ",
        choices:["げつ","が","き"]
    },
    {
        kanji:"火",
        answer:"か",
        choices:["か","ひい","が"]
    },
    {
        kanji:"水曜日",
        answer:"すいようび",
        choices:["すいようび","かようび","きんようび"]
    },
    {
        kanji:"木曜日",
        answer:"もくようび",
        choices:["すいようび","もくようび","きんようび"]
    },
    {
        kanji:"金曜日",
        answer:"きんようび",
        choices:["すいようび","かようび","きんようび"]
    },
    {
        kanji:"土曜日",
        answer:"どようび",
        choices:["どようび","かようび","きんようび"]
    },
    {
        kanji:"日曜日",
        answer:"にちようび",
        choices:["すいようび","にちようび","きんようび"]
    },
    {
        kanji:"～曜日",
        answer:"～ようび",
        choices:["～ようび","～ようひ","～よび"]
    },
    {
        kanji:"朝",
        answer:"あさ",
        choices:["あさ","ちょうし","あした"]
    },
    {
        kanji:"昼",
        answer:"ひる",
        choices:["ひる","ちゅうう","ひろ"]
    },
    {
        kanji:"夜",
        answer:"よる",
        choices:["よる","やい","よい"]
    },
    {
        kanji:"～時",
        answer:"～じ",
        choices:["～じ","～ひ","～し"]
    },
    {
        kanji:"～分",
        answer:"～ふん",
        choices:["～ふん","～ぶん","～ん"]
    },
    {
        kanji:"～半",
        answer:"～はん",
        choices:["～はん","～ばん","～ぱん"]
    },
    {
        kanji:"～枚",
        answer:"～まい",
        choices:["～まい","～ばい","～めい"]
    },
    {
        kanji:"読みます",
        answer:"よみます",
        choices:["よみます","よびます","みます"]
    },
    {
        kanji:"聞きます",
        answer:"ききます",
        choices:["ききます","ききした","よみます"]
    },
    {
        kanji:"見ます",
        answer:"みます",
        choices:["みます","きます","よみます"]
    },
    {
        kanji:"本",
        answer:"ほん",
        choices:["ほん","びん","ぽん"]
    },
    {
        kanji:"友だち",
        answer:"ともだち",
        choices:["ともだち","ともたち","ゆうだち"]
    },
    {
        kanji:"何",
        answer:"なに",
        choices:["なに","なし","なんに"]
    },
    {
        kanji:"～年",
        answer:"～ねん",
        choices:["～ねん","～ねい","～せい"]
    },
    {
        kanji:"～月",
        answer:"～がつ",
        choices:["～がつ","～げぃ","～き"]
    },
    {
        kanji:"～日",
        answer:"～にち",
        choices:["～にち","～じ","～ぎ"]
    },
    {
        kanji:"今日",
        answer:"きょう",
        choices:["きょう","こんに","きょ"]
    },
    {
        kanji:"今週",
        answer:"こんしゅう",
        choices:["こんしゅう","こんじゅう","こんしょう"]
    },
    {
        kanji:"今度",
        answer:"こんど",
        choices:["こんど","こんと","いまど"]
    },

    {
        kanji:"東",
        answer:"ひがし",
        choices:["ひがし","あ","とお"]
    },
    {
        kanji:"西",
        answer:"にし",
        choices:["にし","せ","さ"]
    },
    {
        kanji:"南",
        answer:"みなみ",
        choices:["みなみ","な","なみ"]
    },
    {
        kanji:"北",
        answer:"きた",
        choices:["きた","ほ","きだ"]
    },
    {
        kanji:"会社",
        answer:"かいしゃ",
        choices:["かいしゃ","がいしゃ","かしゃ"]
    },
    {
        kanji:"来ます",
        answer:"きます",
        choices:["きます","いきます","きました"]
    },
    {
        kanji:"行きます",
        answer:"いきます",
        choices:["いきます","きます","のります"]
    },
    {
        kanji:"乗ります",
        answer:"のります",
        choices:["のります","おります","いきます"]
    },
    {
        kanji:"大きい",
        answer:"おおきい",
        choices:["おおきい","おきい","だいきい"]
    },
    {
        kanji:"小さい",
        answer:"ちいさい",
        choices:["ちいさい","こさい","ちさい"]
    },
    {
        kanji:"高い",
        answer:"たかい",
        choices:["たかい","こうい","たけい"]
    },
    {
        kanji:"低い",
        answer:"ひくい",
        choices:["ひくい","ていい","ひきい"]
    },
    {
        kanji:"前",
        answer:"まえ",
        choices:["まえ","うしろ","まい"]
    },
    {
        kanji:"後ろ",
        answer:"うしろ",
        choices:["うしろ","まえ","あとろ"]
    },
    {
        kanji:"横",
        answer:"よこ",
        choices:["よこ","お","よけ"]
    },
    {
        kanji:"入口",
        answer:"いりぐち",
        choices:["いりぐち","でぐち","いりくち"]
    },
    {
        kanji:"出口",
        answer:"でぐち",
        choices:["でぐち","いりぐち","でくち"]
    },
    {
        kanji:"～階",
        answer:"～かい",
        choices:["～かい","～が","～けい"]
    },
    {
        kanji:"押す",
        answer:"おす",
        choices:["おす","ひく","おろす"]
    },
    {
        kanji:"引く",
        answer:"ひく",
        choices:["ひく","おす","ひらく"]
    },
    {
        kanji:"安い",
        answer:"やすい",
        choices:["やすい","やさい","あんい"]
    },
    {
        kanji:"一",
        answer:"いち",
        choices:["いち","に","さん"]
    },
    {
        kanji:"二",
        answer:"に",
        choices:["に","いち","さん"]
    },
    {
        kanji:"三",
        answer:"さん",
        choices:["さん","に","よん"]
    },
    {
        kanji:"四",
        answer:"よん",
        choices:["よん","し","ご"]
    },
    {
        kanji:"五",
        answer:"ご",
        choices:["ご","ろく","しち"]
    },
    {
        kanji:"六",
        answer:"ろく",
        choices:["ろく","ご","なな"]
    },
    {
        kanji:"七",
        answer:"なな",
        choices:["なな","しち","はち"]
    },
    {
        kanji:"八",
        answer:"はち",
        choices:["はち","なな","きゅう"]
    },
    {
        kanji:"九",
        answer:"きゅう",
        choices:["きゅう","く","はち"]
    },
    {
        kanji:"十",
        answer:"じゅう",
        choices:["じゅう","きゅう","とお"]
    },
    
    {
        kanji:"百",
        answer:"ひゃく",
        choices:["ひゃく","びゃ","ひゃっく"]
    },
    {
        kanji:"千",
        answer:"せん",
        choices:["せん","ぜん","せい"]
    },
    {
        kanji:"万",
        answer:"まん",
        choices:["まん","ば","もん"]
    },
    {
        kanji:"～円",
        answer:"～えん",
        choices:["～えん","～せん","～えい"]
    },
    {
        kanji:"休み",
        answer:"やすみ",
        choices:["やすみ","やすめ","きゅうみ"]
    },
    {
        kanji:"映画",
        answer:"えいが",
        choices:["えいが","えが","えいか"]
    },
    {
        kanji:"日本語",
        answer:"にほんご",
        choices:["にほんご","にっぽんご","にほんこ"]
    },
    {
        kanji:"勉強します",
        answer:"べんきょうします",
        choices:["べんきょうします","べんこうします","べんきょします"]
    },
    {
        kanji:"買います",
        answer:"かいます",
        choices:["かいます","かえます","がいます"]
    },

    {
        kanji:"温泉",
        answer:"おんせん",
        choices:["おんせん","おんぜん","おせん"]
    },
    {
        kanji:"予定",
        answer:"よてい",
        choices:["よてい","ようてい","よたい"]
    },
    {
        kanji:"来週",
        answer:"らいしゅう",
        choices:["らいしゅう","らいしょう","らいじゅう"]
    },
    {
        kanji:"会います",
        answer:"あいます",
        choices:["あいます","かいます","あります"]
    },
    {
        kanji:"入ります",
        answer:"はいります",
        choices:["はいります","いります","はいれます"]
    },
    {
        kanji:"旅行します",
        answer:"りょこうします",
        choices:["りょこうします","りょうこうします","りょこします"]
    },

    {
        kanji:"学生",
        answer:"がくせい",
        choices:["がくせい","かくせい","がくしょう"]
    },
    {
        kanji:"学校",
        answer:"がっこう",
        choices:["がっこう","がこう","かっこう"]
    },
    {
        kanji:"生活",
        answer:"せいかつ",
        choices:["せいかつ","しょうかつ","せいがつ"]
    },
    {
        kanji:"去年",
        answer:"きょねん",
        choices:["きょねん","こねん","きょうねん"]
    },
    {
        kanji:"先週",
        answer:"せんしゅう",
        choices:["せんしゅう","せんしょう","せんじゅう"]
    },
    {
        kanji:"仕事",
        answer:"しごと",
        choices:["しごと","じごと","しこと"]
    },
    {
        kanji:"元気",
        answer:"げんき",
        choices:["げんき","けんき","げんぎ"]
    },
    {
        kanji:"忙しい",
        answer:"いそがしい",
        choices:["いそがしい","いぞがしい","いそかしい"]
    },
    {
        kanji:"働く",
        answer:"はたらく",
        choices:["はたらく","はらたく","はたろく"]
    },
    {
        kanji:"作る",
        answer:"つくる",
        choices:["つくる","さくる","つぐる"]
    },

    {
        kanji:"人",
        answer:"ひと",
        choices:["ひと","じ","に"]
    },
    {
        kanji:"～人",
        answer:"～にん",
        choices:["～にん","～じ","～ひ"]
    },
    {
        kanji:"犬",
        answer:"いぬ",
        choices:["いぬ","け","いね"]
    },
    {
        kanji:"家族",
        answer:"かぞく",
        choices:["かぞく","かそく","かぞっく"]
    },
    {
        kanji:"夕方",
        answer:"ゆうがた",
        choices:["ゆうがた","ゆがた","ゆうかた"]
    },
    {
        kanji:"英語",
        answer:"えいご",
        choices:["えいご","えご","えいこ"]
    },
    {
        kanji:"音楽",
        answer:"おんがく",
        choices:["おんがく","おんらく","おんかく"]
    },
    {
        kanji:"習う",
        answer:"ならう",
        choices:["ならう","ならぶ","ならえる"]
    },
    {
        kanji:"話す",
        answer:"はなす",
        choices:["はなす","はなし","はなせる"]
    },
    {
        kanji:"出かける",
        answer:"でかける",
        choices:["でかける","でがける","でかいる"]
    },

    {
        kanji:"季節",
        answer:"きせつ",
        choices:["きせつ","ぎせつ","きぜつ"]
    },
    {
        kanji:"春",
        answer:"はる",
        choices:["はる","しゅ","ばる"]
    },
    {
        kanji:"夏",
        answer:"なつ",
        choices:["なつ","か","なち"]
    },
    {
        kanji:"秋",
        answer:"あき",
        choices:["あき","しゅ","あぎ"]
    },
    {
        kanji:"冬",
        answer:"ふゆ",
        choices:["ふゆ","と","ふよ"]
    },
    {
        kanji:"花",
        answer:"はな",
        choices:["はな","かな","ばな"]
    },
    {
        kanji:"同じ",
        answer:"おなじ",
        choices:["おなじ","どうじ","おなし"]
    },
    {
        kanji:"暑い",
        answer:"あつい",
        choices:["あつい","あづい","ねつい"]
    },
    {
        kanji:"寒い",
        answer:"さむい",
        choices:["さむい","ざむい","かんい"]
    },
    {
        kanji:"天気",
        answer:"てんき",
        choices:["てんき","でんき","てんぎ"]
    },
    {
        kanji:"晴れ",
        answer:"はれ",
        choices:["はれ","せい","はり"]
    },
    {
        kanji:"雨",
        answer:"あめ",
        choices:["あめ","うう","あみ"]
    },
    {
        kanji:"雪",
        answer:"ゆき",
        choices:["ゆき","せ","ゆぎ"]
    },
    {
        kanji:"風",
        answer:"かぜ",
        choices:["かぜ","ふ","かせ"]
    },
    {
        kanji:"今",
        answer:"いま",
        choices:["いま","こ","いめ"]
    },
    {
        kanji:"昨日",
        answer:"きのう",
        choices:["きのう","さくじ","きょう"]
    },
    {
        kanji:"明日",
        answer:"あした",
        choices:["あした","あず","みょうに"]
    },
    {
        kanji:"毎日",
        answer:"まいにち",
        choices:["まいにち","まいじつ","まいひ"]
    },
    {
        kanji:"強い",
        answer:"つよい",
        choices:["つよい","づよい","きょうい"]
    },

    {
        kanji:"町",
        answer:"まち",
        choices:["まち","ちょ","まじ"]
    },
    {
        kanji:"店",
        answer:"みせ",
        choices:["みせ","て","みぜ"]
    },
    {
        kanji:"食堂",
        answer:"しょくどう",
        choices:["しょくどう","しょくとう","しょくろう"]
    },
    {
        kanji:"便利",
        answer:"べんり",
        choices:["べんり","へんり","べり"]
    },
    {
        kanji:"不便",
        answer:"ふべん",
        choices:["ふべん","ぶべん","ふへん"]
    },
    {
        kanji:"静か",
        answer:"しずか",
        choices:["しずか","せいか","しづか"]
    },
    {
        kanji:"有名",
        answer:"ゆうめい",
        choices:["ゆうめい","ゆめい","ゆうみょう"]
    },
    {
        kanji:"多い",
        answer:"おおい",
        choices:["おおい","おい","たい"]
    },
    {
        kanji:"少ない",
        answer:"すくない",
        choices:["すくない","しょうない","すこない"]
    },
    {
        kanji:"遠い",
        answer:"とおい",
        choices:["とおい","とい","えんい"]
    },

    {
        kanji:"道",
        answer:"みち",
        choices:["みち","ど","みじ"]
    },
    {
        kanji:"公園",
        answer:"こうえん",
        choices:["こうえん","こうねん","こうせん"]
    },
    {
        kanji:"銀行",
        answer:"ぎんこう",
        choices:["ぎんこう","きんこう","ぎんごう"]
    },
    {
        kanji:"お寺",
        answer:"おてら",
        choices:["おてら","おでら","てらり"]
    },
    {
        kanji:"神社",
        answer:"じんじゃ",
        choices:["じんじゃ","しんじゃ","しんしゃ"]
    },
    {
        kanji:"右",
        answer:"みぎ",
        choices:["みぎ","うぎ","みき"]
    },
    {
        kanji:"左",
        answer:"ひだり",
        choices:["ひだり","さい","ひたり"]
    },
    {
        kanji:"近く",
        answer:"ちかく",
        choices:["ちかく","きんく","ちがく"]
    },
    {
        kanji:"車",
        answer:"くるま",
        choices:["くるま","ぐるま","くろま"]
    },
    {
        kanji:"送る",
        answer:"おくる",
        choices:["おくる","おこる","そうる"]
    },

    {
        kanji:"時間",
        answer:"じかん",
        choices:["じかん","しかん","じけん"]
    },
    {
        kanji:"場所",
        answer:"ばしょ",
        choices:["ばしょ","はしょ","ばしょう"]
    },
    {
        kanji:"駅",
        answer:"えき",
        choices:["えき","えぎ","えきい"]
    },
    {
        kanji:"受付",
        answer:"うけつけ",
        choices:["うけつけ","うけづけ","うけせつ"]
    },
    {
        kanji:"門",
        answer:"もん",
        choices:["もん","か","もんう"]
    },
    {
        kanji:"電車",
        answer:"でんしゃ",
        choices:["でんしゃ","てんしゃ","でしゃ"]
    },
    {
        kanji:"待つ",
        answer:"まつ",
        choices:["まつ","もつ","またつ"]
    },
    {
        kanji:"止まる",
        answer:"とまる",
        choices:["とまる","やまる","とめる"]
    },
    {
        kanji:"着く",
        answer:"つく",
        choices:["つく","ちゃく","つける"]
    },
    {
        kanji:"急ぐ",
        answer:"いそぐ",
        choices:["いそぐ","いそく","きゅうぐ"]
    },

    {
        kanji:"お金",
        answer:"おかね",
        choices:["おかね","がね","おがね"]
    },
    {
        kanji:"食事",
        answer:"しょくじ",
        choices:["しょくじ","しょくし","しょくち"]
    },
    {
        kanji:"～店",
        answer:"～てん",
        choices:["～てん","～み","～でん"]
    },
    {
        kanji:"博物館",
        answer:"はくぶつかん",
        choices:["はくぶつかん","はくもつかん","ばくぶつかん"]
    },    {
        kanji:"動物園",
        answer:"どうぶつえん",
        choices:["どうぶつえん","どうぶつせん","どうもつえん"]
    },
    {
        kanji:"試合",
        answer:"しあい",
        choices:["しあい","じあい","しやい"]
    },
    {
        kanji:"楽しい",
        answer:"たのしい",
        choices:["たのしい","たのし","らくしい"]
    },
    {
        kanji:"難しい",
        answer:"むずかしい",
        choices:["むずかしい","むつかしい","むずしい"]
    },
    {
        kanji:"登る",
        answer:"のぼる",
        choices:["のぼる","のぼれる","あがる"]
    },

];
